/*Listar el Nro de Lector, Nombre y fecha de Préstamo de aquellos Lectores que hayan
realizado un préstamo y no lo hayan devuelto*/

SELECT LEC.NRO_LECTOR AS 'NUM. LECTOR', LEC.NOMBRE AS NOMBRE, PRES.F_PREST AS 'FECHA PRESTAMO'
FROM LECTOR LEC
JOIN PRESTAMO PRES
ON LEC.NRO_LECTOR = PRES.NRO_LECTOR 
WHERE LEC.NRO_LECTOR IN (
SELECT NRO_LECTOR
FROM PRESTAMO
GROUP BY NRO_LECTOR 
HAVING MIN(F_DEVOL) IS NULL);