/*Listar Nro de Lector, Nombre, nro de Libro, Titulo, fecha de préstamo que aquellos
Prestamos que hayan sido devueltos*/

SELECT PRES.NRO_LECTOR AS 'NRO LECTOR', LEC.NOMBRE AS NOMBRE, PRES.NRO_LIBRO AS 'NRO. LIBRO', LIB.TITULO AS TITULO, PRES.F_PREST AS 'FECHA PRESTAMO'
FROM PRESTAMO PRES
JOIN LECTOR LEC
ON PRES.NRO_LECTOR = LEC.NRO_LECTOR
JOIN LIBRO LIB
ON PRES.NRO_LIBRO = LIB.NRO_LIBRO
WHERE PRES.F_DEVOL IS NOT NULL;