/*Listar el Nro de Libro, Titulo, fecha de Préstamo y la fecha de Devolución de los Libros
prestados*/
SELECT PRESTAMO.NRO_LIBRO, TITULO, F_PREST,F_DEVOL 
FROM PRESTAMO LEFT JOIN LIBRO on PRESTAMO.NRO_LIBRO = LIBRO.NRO_LIBRO

SELECT LIBRO.NRO_LIBRO,LIBRO.TITULO, PRESTAMO.F_PREST, PRESTAMO.F_DEVOL
FROM LIBRO INNER JOIN PRESTAMO ON LIBRO.NRO_LIBRO = PRESTAMO.NRO_LIBRO

/*LAS DOS FORMAS QUEDAN IGUAL*/

