/*. Listar el número de lector, su nombre y la cantidad de préstamos realizados a ese
lector.*/




SELECT MAX(LECTOR.NOMBRE) AS 'NOMBRE LECTOR', LECTOR.NRO_LECTOR, COUNT(PRESTAMO.NRO_LECTOR) AS 'CANTIDAD PRESTAMO'
FROM LECTOR INNER JOIN PRESTAMO ON LECTOR.NRO_LECTOR = PRESTAMO.NRO_LECTOR
GROUP BY LECTOR.NRO_LECTOR


SELECT (LECTOR.NOMBRE) AS 'NOMBRE LECTOR', LECTOR.NRO_LECTOR, COUNT(PRESTAMO.NRO_LECTOR) AS 'CANTIDAD PRESTAMO'
FROM LECTOR INNER JOIN PRESTAMO ON LECTOR.NRO_LECTOR = PRESTAMO.NRO_LECTOR
GROUP BY LECTOR.NRO_LECTOR, LECTOR.NOMBRE

/* EN LA PRIMERA PONGO MAX(LEC..) PARA EVITAR EL GROUP BY CON LECTOR NOMBRE PORQUE NO PUEDO TENER COLUMNAS SIN QUE SEAN AGREGACIONES, 
EN ESTE CASO NO ME DECIAN ESPECIFICAMENTE POR QUE AGRUPAR NI NADA, POR ESO PONGO LOS DOS EJ*/