/*Realizar una sentencia SQL que involucre TODOS los campos de TODAS las tablas
¿Es esto posible?*/


SELECT * 
FROM PRESTAMO PRES
INNER JOIN LECTOR LEC
ON PRES.NRO_LECTOR = LEC.NRO_LECTOR
INNER JOIN LIBRO LIB
ON PRES.NRO_LIBRO = LIB.NRO_LIBRO
INNER JOIN TIPOLIBRO TLIB
ON LIB.TIPO = TLIB.TIPO
INNER JOIN COPIAS COPIA
ON (PRES.NRO_LIBRO = COPIA.NRO_LIBRO AND PRES.NRO_COPIA = COPIA.NRO_COPIA);